# Generated by Django 4.2.6 on 2023-10-10 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=255)),
                ('Durable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('SupplierId', models.AutoField(primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UnitsInStock', models.IntegerField()),
                ('UnitsOnOrder', models.IntegerField()),
                ('UnitsSoldInStore', models.IntegerField()),
                ('Suspended', models.BooleanField(default=False)),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.categories')),
                ('SupplierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.suppliers')),
            ],
        ),
    ]
